$COFFEE = File.expand_path("node_modules/.bin/coffee")

rule ".json" => ".coffee" do |target|
  sh "#{$COFFEE} ../../bin/c2json.coffee #{target.source} #{target.name}"
end

task "build" => %w[
  build:json
  browser/bundle.min.js
]

task "build:json" => %w[
  api/schema.json
  api/interface.json
  api/map.json
]

task "test" => "build:json" do
  sh "#{$COFFEE} test/client_test.coffee"
end

task "browserify" do
  command = "node_modules/.bin/browserify "
  command << "-r ./test/client_test.coffee "
  command << "-i zlib "
  command << "-o browser/bundle.js"
  sh command

end

file "browser/bundle.min.js" => "browser/bundle.js" do |target|
  sh "node_modules/.bin/uglifyjs -o #{target.name} browser/bundle.js"
end

file "browser/bundle.js" => "test/client_test.coffee" do |target|
  command = "node_modules/.bin/browserify "
  command << "-r ./test/client_test.coffee "
  command << "-i zlib "
  command << "-o browser/bundle.js"
  sh command
end

