// Generated by CoffeeScript 1.3.3
var JSV, SchemaValidator;

JSV = require("JSV").JSV;

SchemaValidator = (function() {

  function SchemaValidator() {
    this.jsv = JSV.createEnvironment("json-schema-draft-03");
  }

  SchemaValidator.prototype.register_schema = function(schema) {
    return this.jsv.createSchema(schema, false, schema.id);
  };

  SchemaValidator.prototype.get_schema = function(type) {
    var schema_url;
    if (type.indexOf("#") === 0) {
      schema_url = "urn:" + this.application_schema.id + type;
    } else {
      schema_url = "urn:" + type;
    }
    return this.jsv.findSchema(schema_url);
  };

  SchemaValidator.prototype.validate = function(type, data) {
    var schema;
    schema = this.get_schema(type);
    if (schema) {
      return this.jsv.validate(data, schema, function(error) {
        return console.log(error);
      });
    } else {
      throw "unknown schema type: " + type;
    }
  };

  return SchemaValidator;

})();

module.exports = SchemaValidator;
