// Generated by CoffeeScript 1.3.3
var Client, Shred, patchboard_api, patchboard_interface, patchboard_resources, patchboard_schema;

Shred = require("shred");

patchboard_api = require("./patchboard_api");

patchboard_schema = patchboard_api.schema;

patchboard_interface = patchboard_api["interface"];

patchboard_resources = patchboard_api.resources;

Client = (function() {

  Client.discover = function(service_url, callback) {
    return new Shred().request({
      url: service_url,
      method: "GET",
      headers: {
        "Accept": "application/json"
      },
      on: {
        200: function(response) {
          var client;
          client = new Client(response.content.data);
          return callback(null, client);
        },
        error: function(response) {
          return callback(response);
        }
      }
    });
  };

  function Client(options) {
    var absolute_name, definition, key, merged, name, parent, parent_type, resource_type, schema, value, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    this.shred = new Shred();
    this.schema_id = options.schema.id;
    this.schemas = options.schema.properties;
    this.directory = options.directory;
    this.resources = {};
    _ref = patchboard_schema.properties;
    for (name in _ref) {
      schema = _ref[name];
      absolute_name = "" + patchboard_schema.id + "#" + name;
      this.schemas[absolute_name] = schema;
      this.schemas[name] = schema;
    }
    this["interface"] = {};
    for (key in patchboard_interface) {
      value = patchboard_interface[key];
      this["interface"][key] = value;
    }
    _ref1 = options["interface"];
    for (key in _ref1) {
      value = _ref1[key];
      this["interface"][key] = value;
    }
    this.wrappers = {};
    _ref2 = this.schemas;
    for (resource_type in _ref2) {
      schema = _ref2[resource_type];
      if (resource_type === "patchboard#resource") {
        continue;
      }
      if (schema["extends"]) {
        parent_type = schema["extends"].$ref;
        if ((parent_type != null ? parent_type.indexOf("#") : void 0) === 0) {
          parent = this.schemas[parent_type.slice(1)];
        } else {
          parent = this.schemas[parent_type];
        }
        merged = {
          properties: {}
        };
        _ref3 = parent.properties;
        for (key in _ref3) {
          value = _ref3[key];
          merged.properties[key] = value;
        }
        _ref4 = schema.properties;
        for (key in _ref4) {
          value = _ref4[key];
          merged.properties[key] = value;
        }
        schema.properties = merged.properties;
      } else if (schema.type === "array") {
        this.wrappers[resource_type] = this.array_wrapper(schema);
      } else if (schema.type === "object") {
        this.wrappers[resource_type] = this.object_wrapper(schema);
      }
    }
    _ref5 = this["interface"];
    for (resource_type in _ref5) {
      definition = _ref5[resource_type];
      if (schema = this.schemas[resource_type]) {
        this.wrappers[resource_type] = this.resource_wrapper(resource_type, schema);
      }
    }
    this.create_resources(this.directory);
  }

  Client.prototype.create_resources = function(directory) {
    var key, value, _results;
    _results = [];
    for (key in directory) {
      value = directory[key];
      if (this.wrappers[key]) {
        _results.push(this.resources[key] = new this.wrappers[key]({
          url: value
        }));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  Client.prototype.array_wrapper = function(schema) {
    var client, item_type;
    client = this;
    item_type = this.munge_type(schema.items);
    return function(items) {
      var result, value, _i, _len;
      result = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        value = items[_i];
        result.push(client.wrap(item_type, value));
      }
      return result;
    };
  };

  Client.prototype.munge_type = function(schema) {
    if (schema.$ref) {
      return schema.$ref.slice(1);
    } else if (schema.type) {
      return schema.type;
    }
  };

  Client.prototype.object_wrapper = function(schema) {
    var client;
    client = this;
    return function(data) {
      var name, prop_def, raw, type, wrapped, _ref;
      _ref = schema.properties;
      for (name in _ref) {
        prop_def = _ref[name];
        raw = data[name];
        type = client.munge_type(prop_def);
        if (type) {
          wrapped = client.wrap(type, raw);
        } else {
          wrapped = raw;
        }
        data[name] = wrapped;
      }
      if (schema.additionalProperties) {
        type = client.munge_type(schema.additionalProperties);
        if (type) {
          for (name in data) {
            raw = data[name];
            if (!(schema.properties && schema.properties[name])) {
              data[name] = client.wrap(type, raw);
            }
          }
        }
      }
      return data;
    };
  };

  Client.prototype.resource_wrapper = function(resource_type, schema) {
    var client, constructor, interface_def;
    client = this;
    constructor = this.resource_constructor();
    constructor.resource_type = resource_type;
    if (interface_def = this["interface"][resource_type]) {
      this.define_interface(constructor, interface_def.actions);
    }
    this.define_properties(constructor, schema.properties);
    return function(data) {
      return new constructor(data);
    };
  };

  Client.prototype.define_interface = function(constructor, actions) {
    var definition, method, name, _ref, _results;
    constructor.prototype.requests = {};
    _ref = this.resource_prototype;
    for (name in _ref) {
      method = _ref[name];
      constructor.prototype[name] = method;
    }
    _results = [];
    for (name in actions) {
      definition = actions[name];
      constructor.prototype.requests[name] = this.request_creator(name, definition);
      _results.push(constructor.prototype[name] = this.register_action(name));
    }
    return _results;
  };

  Client.prototype.define_properties = function(constructor, properties) {
    var client, name, schema, spec, _results;
    client = this;
    _results = [];
    for (name in properties) {
      schema = properties[name];
      spec = this.property_spec(name, schema);
      _results.push(Object.defineProperty(constructor.prototype, name, spec));
    }
    return _results;
  };

  Client.prototype.property_spec = function(name, property_schema) {
    var client, spec, wrap_function;
    client = this;
    wrap_function = this.create_wrapping_function(name, property_schema);
    spec = {};
    spec.get = function() {
      var val;
      val = this.properties[name];
      return wrap_function(val);
    };
    if (!property_schema.readonly) {
      spec.set = function(val) {
        return this.properties[name] = val;
      };
    }
    return spec;
  };

  Client.prototype.resource_constructor = function() {
    var client;
    client = this;
    return function(properties) {
      Object.defineProperty(this, "client", {
        value: client,
        enumerable: false
      });
      this.properties = properties;
      return null;
    };
  };

  Client.prototype.resource_prototype = {
    prepare_request: function(name, options) {
      var prepper;
      prepper = this.requests[name];
      if (prepper) {
        return prepper.call(this, name, options);
      } else {
        throw "No such action defined: " + name;
      }
    },
    request: function(name, options) {
      var request;
      request = this.prepare_request(name, options);
      return this.client.shred.request(request);
    },
    credential: function(type, action) {
      var cap;
      if (type === "Capability") {
        return cap = this.properties.capabilities[action];
      }
    }
  };

  Client.prototype.register_action = function(name) {
    return function(data) {
      return this.request(name, data);
    };
  };

  Client.prototype.request_creator = function(name, definition) {
    var authorization, client, default_headers, method, query, request_media_type, request_type, required_params, response_media_type, response_type;
    client = this;
    method = definition.method;
    default_headers = {};
    if (request_type = definition.request_entity) {
      request_media_type = client.schemas[request_type].mediaType;
      default_headers["Content-Type"] = request_media_type;
    }
    if (response_type = definition.response_entity) {
      response_media_type = client.schemas[response_type].mediaType;
      default_headers["Accept"] = response_media_type;
    }
    authorization = definition.authorization;
    if (query = definition.query) {
      required_params = query.required;
    }
    return function(name, options) {
      var credential, error, handler, key, request, response, status, value, _ref, _ref1;
      request = {
        url: this.url,
        method: method,
        headers: {},
        content: options.content
      };
      for (key in default_headers) {
        value = default_headers[key];
        request.headers[key] = value;
      }
      if (authorization) {
        credential = this.credential(authorization, name);
        request.headers["Authorization"] = "" + authorization + " " + credential;
      }
      _ref = options.headers;
      for (name in _ref) {
        value = _ref[name];
        request.headers[name] = value;
      }
      if (options.query) {
        request.query = options.query;
      }
      for (key in required_params) {
        value = required_params[key];
        if (!request.query[key]) {
          throw "Missing required query param: " + key;
        }
      }
      request.on = {};
      if (error = options.on.error) {
        request.on.error = error;
        delete options.on.error;
      }
      if (response = options.on.response) {
        request.on.response = response;
        delete options.on.response;
      }
      _ref1 = options.on;
      for (status in _ref1) {
        handler = _ref1[status];
        request.on[status] = function(response) {
          var wrapped;
          wrapped = client.wrap(response_type, response.content.data);
          return handler(response, wrapped);
        };
      }
      return request;
    };
  };

  Client.prototype.create_wrapping_function = function(name, schema) {
    var client;
    client = this;
    if (schema.type === "object") {
      return this.object_wrapper(schema);
    } else if (schema.type === "array") {
      return this.array_wrapper(schema);
    } else if (this.wrappers[schema.type]) {
      return function(data) {
        return client.wrap(schema.type, data);
      };
    } else {
      return function(data) {
        return data;
      };
    }
  };

  Client.prototype.wrap = function(type, data) {
    var wrapper;
    if (wrapper = this.wrappers[type]) {
      return wrapper(data);
    } else {
      return data;
    }
  };

  return Client;

})();

module.exports = Client;
