// Generated by CoffeeScript 1.3.3
var JSV, SchemaValidator;

JSV = require("JSV").JSV;

SchemaValidator = (function() {

  function SchemaValidator(schema_manager) {
    var schema, _i, _len, _ref;
    this.schema_manager = schema_manager;
    this.jsv = JSV.createEnvironment("json-schema-draft-03");
    _ref = this.schema_manager.schemas;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      schema = _ref[_i];
      this.jsv.createSchema(schema, false, schema.id);
    }
  }

  SchemaValidator.prototype.validate = function(identifier, data) {
    var error, propname, result, schema, _i, _len, _ref;
    schema = this.schema_manager.find(identifier);
    if (schema) {
      result = this.jsv.findSchema(schema.id).validate(data, schema);
      if (result.errors) {
        result.description = {};
        _ref = result.errors;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          error = _ref[_i];
          propname = error.schemaUri.split(":")[2];
          result.description[propname] = error.message;
        }
      }
      return result;
    } else {
      throw "unknown schema id: " + id;
    }
  };

  return SchemaValidator;

})();

module.exports = SchemaValidator;
