
desc "Run tests"
task "test" do
  sh "coffee test/path_matcher_test.coffee"
  sh "coffee test/schema_manager_test.coffee"
  sh "coffee test/classifier_test.coffee"
end

rule ".json" => ".coffee" do |target|
  sh "coffee bin/c2json.coffee #{target.source} #{target.name}"
end



